#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION_FULL "2019.3.11f1_ceef2d848e70"
#define UNITY_VERSION_FULL_NICE "2019.3.11f1 (ceef2d848e70)"
#define UNITY_VERSION_BLD 13561645
#define UNITY_VERSION_DATE 1587440709
#define UNITY_VERSION_WIN "2019.3.11.13561645"
#define UNITY_VERSION_BRANCH "2019.3/staging"
